export const routeManifest = [
  { label: 'Page 404', originalFile: '404.html', route: '/404', component: 'Page404', status: 'pending_ui_fix' },
  { label: 'About Us 2', originalFile: 'about-us-2.html', route: '/about-2', component: 'AboutUs2', status: 'pending_ui_fix' },
  { label: 'About Us', originalFile: 'about-us.html', route: '/about', component: 'AboutUs', status: 'pending_ui_fix' },
  { label: 'Blog Details Fullwidth', originalFile: 'blog-details-fullwidth.html', route: '/blog/details/fullwidth', component: 'BlogDetailsFullwidth', status: 'pending_ui_fix' },
  { label: 'Blog Details Left Sidebar', originalFile: 'blog-details-left-sidebar.html', route: '/blog-details-left-sidebar', component: 'BlogDetailsLeftSidebar', status: 'pending_ui_fix' },
  { label: 'Blog Details Right Sidebar', originalFile: 'blog-details-right-sidebar.html', route: '/blog-details-right-sidebar', component: 'BlogDetailsRightSidebar', status: 'pending_ui_fix' },
  { label: 'Blog Fullwidth', originalFile: 'blog-fullwidth.html', route: '/blog-fullwidth', component: 'BlogFullwidth', status: 'pending_ui_fix' },
  { label: 'Blog Grid Fullwidth', originalFile: 'blog-grid-fullwidth.html', route: '/blog/grid-fullwidth', component: 'BlogGridFullwidth', status: 'pending_ui_fix' },
  { label: 'Blog Grid Left Sidebar', originalFile: 'blog-grid-left-sidebar.html', route: '/blog-grid-left-sidebar', component: 'BlogGridLeftSidebar', status: 'pending_ui_fix' },
  { label: 'Blog Grid Right Sidebar', originalFile: 'blog-grid-right-sidebar.html', route: '/blog-grid-right-sidebar', component: 'BlogGridRightSidebar', status: 'pending_ui_fix' },
  { label: 'Blog Left Sidebar', originalFile: 'blog-left-sidebar.html', route: '/blog-left-sidebar', component: 'BlogLeftSidebar', status: 'pending_ui_fix' },
  { label: 'Blog List Fullwidth', originalFile: 'blog-list-fullwidth.html', route: '/blog-list-fullwidth', component: 'BlogListFullwidth', status: 'pending_ui_fix' },
  { label: 'Blog List Left Sidebar', originalFile: 'blog-list-left-sidebar.html', route: '/blog-list-left-sidebar', component: 'BlogListLeftSidebar', status: 'pending_ui_fix' },
  { label: 'Blog List Right Sidebar', originalFile: 'blog-list-right-sidebar.html', route: '/blog-list-right-sidebar', component: 'BlogListRightSidebar', status: 'pending_ui_fix' },
  { label: 'Blog Masonry Fullwidth', originalFile: 'blog-masonry-fullwidth.html', route: '/blog-masonry-fullwidth', component: 'BlogMasonryFullwidth', status: 'pending_ui_fix' },
  { label: 'Blog Masonry Left Sidebar', originalFile: 'blog-masonry-left-sidebar.html', route: '/blog-masonry-left-sidebar', component: 'BlogMasonryLeftSidebar', status: 'pending_ui_fix' },
  { label: 'Blog Masonry Right Sidebar', originalFile: 'blog-masonry-right-sidebar.html', route: '/blog-masonry-right-sidebar', component: 'BlogMasonryRightSidebar', status: 'pending_ui_fix' },
  { label: 'Blog Right Sidebar', originalFile: 'blog-right-sidebar.html', route: '/blog-right-sidebar', component: 'BlogRightSidebar', status: 'pending_ui_fix' },
  { label: 'Checkout', originalFile: 'checkout.html', route: '/checkout', component: 'Checkout', status: 'pending_ui_fix' },
  { label: 'Coming Soon', originalFile: 'coming-soon.html', route: '/coming-soon', component: 'ComingSoon', status: 'pending_ui_fix' },
  { label: 'Contact Us', originalFile: 'contact-us.html', route: '/contact', component: 'ContactUs', status: 'pending_ui_fix' },
  { label: 'Elements Brands', originalFile: 'elements-brands.html', route: '/elements-brands', component: 'ElementsBrands', status: 'pending_ui_fix' },
  { label: 'Elements Buttons', originalFile: 'elements-buttons.html', route: '/elements-buttons', component: 'ElementsButtons', status: 'pending_ui_fix' },
  { label: 'Elements Category Banner', originalFile: 'elements-category-banner.html', route: '/elements-category-banner', component: 'ElementsCategoryBanner', status: 'pending_ui_fix' },
  { label: 'Elements FAQ', originalFile: 'elements-faq.html', route: '/elements-faq', component: 'ElementsFAQ', status: 'pending_ui_fix' },
  { label: 'Elements Icon Box', originalFile: 'elements-icon-box.html', route: '/elements-icon-box', component: 'ElementsIconBox', status: 'pending_ui_fix' },
  { label: 'Elements Instagram', originalFile: 'elements-instagram.html', route: '/elements-instagram', component: 'ElementsInstagram', status: 'pending_ui_fix' },
  { label: 'Elements Map', originalFile: 'elements-map.html', route: '/elements-map', component: 'ElementsMap', status: 'pending_ui_fix' },
  { label: 'Elements Product Sale Banner', originalFile: 'elements-product-sale-banner.html', route: '/elements-product-sale-banner', component: 'ElementsProductSaleBanner', status: 'pending_ui_fix' },
  { label: 'Elements Products Tabs', originalFile: 'elements-products-tabs.html', route: '/elements-products-tabs', component: 'ElementsProductsTabs', status: 'pending_ui_fix' },
  { label: 'Elements Products', originalFile: 'elements-products.html', route: '/elements-products', component: 'ElementsProducts', status: 'pending_ui_fix' },
  { label: 'Elements Team', originalFile: 'elements-team.html', route: '/elements-team', component: 'ElementsTeam', status: 'pending_ui_fix' },
  { label: 'Elements Testimonials', originalFile: 'elements-testimonials.html', route: '/elements-testimonials', component: 'ElementsTestimonials', status: 'pending_ui_fix' },
  { label: 'Home 10', originalFile: 'index-10.html', route: '/home-10', component: 'Index10', status: 'pending_ui_fix' },
  { label: 'Home 11', originalFile: 'index-11.html', route: '/home-11', component: 'Index11', status: 'pending_ui_fix' },
  { label: 'Home (Decor Thriving)', originalFile: 'index-2.html', route: '/home-2', component: 'Index2', status: 'pending_ui_fix' },
  { label: 'Home 3', originalFile: 'index-3.html', route: '/home-3', component: 'Index3', status: 'pending_ui_fix' },
  { label: 'Home 4', originalFile: 'index-4.html', route: '/home-4', component: 'Index4', status: 'pending_ui_fix' },
  { label: 'Home 5', originalFile: 'index-5.html', route: '/home-5', component: 'Index5', status: 'pending_ui_fix' },
  { label: 'Home 6', originalFile: 'index-6.html', route: '/home-6', component: 'Index6', status: 'pending_ui_fix' },
  { label: 'Home 7', originalFile: 'index-7.html', route: '/home-7', component: 'Index7', status: 'pending_ui_fix' },
  { label: 'Home 8', originalFile: 'index-8.html', route: '/home-8', component: 'Index8', status: 'pending_ui_fix' },
  { label: 'Home 9', originalFile: 'index-9.html', route: '/home-9', component: 'Index9', status: 'pending_ui_fix' },
  { label: 'Home (Arts Propelled)', originalFile: 'index.html', route: '/', component: 'Index', status: 'active' },
  { label: 'Login & Register', originalFile: 'login-register.html', route: '/login', component: 'LoginRegister', status: 'pending_ui_fix' },
  { label: 'Lost Password', originalFile: 'lost-password.html', route: '/lost-password', component: 'LostPassword', status: 'pending_ui_fix' },
  { label: 'My Account', originalFile: 'my-account.html', route: '/my-account', component: 'MyAccount', status: 'pending_ui_fix' },
  { label: 'Order Tracking', originalFile: 'order-tracking.html', route: '/order-tracking', component: 'OrderTracking', status: 'pending_ui_fix' },
  { label: 'Portfolio 3 Columns', originalFile: 'portfolio-3-columns.html', route: '/portfolio-3-columns', component: 'Portfolio3Columns', status: 'pending_ui_fix' },
  { label: 'Portfolio 4 Columns', originalFile: 'portfolio-4-columns.html', route: '/portfolio-4-columns', component: 'Portfolio4Columns', status: 'pending_ui_fix' },
  { label: 'Portfolio 5 Columns', originalFile: 'portfolio-5-columns.html', route: '/portfolio-5-columns', component: 'Portfolio5Columns', status: 'pending_ui_fix' },
  { label: 'Portfolio Details', originalFile: 'portfolio-details.html', route: '/portfolio-details', component: 'PortfolioDetails', status: 'pending_ui_fix' },
  { label: 'Product Details 360', originalFile: 'product-details-360.html', route: '/product-details-360', component: 'ProductDetailsThreeSixty', status: 'pending_ui_fix' },
  { label: 'Product Details Background', originalFile: 'product-details-background.html', route: '/product-details-background', component: 'ProductDetailsBackground', status: 'pending_ui_fix' },
  { label: 'Product Details Extra Content', originalFile: 'product-details-extra-content.html', route: '/product-details-extra-content', component: 'ProductDetailsExtraContent', status: 'pending_ui_fix' },
  { label: 'Product Details Fullwidth', originalFile: 'product-details-fullwidth.html', route: '/product-details-fullwidth', component: 'ProductDetailsFullwidth', status: 'pending_ui_fix' },
  { label: 'Product Details Group', originalFile: 'product-details-group.html', route: '/product-details-group', component: 'ProductDetailsGroup', status: 'pending_ui_fix' },
  { label: 'Product Details Image Variation', originalFile: 'product-details-image-variation.html', route: '/product-details-image-variation', component: 'ProductDetailsImageVariation', status: 'pending_ui_fix' },
  { label: 'Product Details Sidebar', originalFile: 'product-details-sidebar.html', route: '/product-details-sidebar', component: 'ProductDetailsSidebar', status: 'pending_ui_fix' },
  { label: 'Product Details Sticky', originalFile: 'product-details-sticky.html', route: '/product-details-sticky', component: 'ProductDetailsSticky', status: 'pending_ui_fix' },
  { label: 'Product Details Basic', originalFile: 'product-details.html', route: '/product-details', component: 'ProductDetails', status: 'pending_ui_fix' },
  { label: 'Shop Fullwidth Left Sidebar', originalFile: 'shop-fullwidth-left-sidebar.html', route: '/shop-fullwidth-left-sidebar', component: 'ShopFullwidthLeftSidebar', status: 'pending_ui_fix' },
  { label: 'Shop Fullwidth No Gutters', originalFile: 'shop-fullwidth-no-gutters.html', route: '/shop-fullwidth-no-gutters', component: 'ShopFullwidthNoGutters', status: 'pending_ui_fix' },
  { label: 'Shop Fullwidth Right Sidebar', originalFile: 'shop-fullwidth-right-sidebar.html', route: '/shop-fullwidth-right-sidebar', component: 'ShopFullwidthRightSidebar', status: 'pending_ui_fix' },
  { label: 'Shop Fullwidth', originalFile: 'shop-fullwidth.html', route: '/shop-fullwidth', component: 'ShopFullwidth', status: 'pending_ui_fix' },
  { label: 'Shop Left Sidebar', originalFile: 'shop-left-sidebar.html', route: '/shop-left-sidebar', component: 'ShopLeftSidebar', status: 'pending_ui_fix' },
  { label: 'Shop Right Sidebar', originalFile: 'shop-right-sidebar.html', route: '/shop-right-sidebar', component: 'ShopRightSidebar', status: 'pending_ui_fix' },
  { label: 'Shop Basic', originalFile: 'shop.html', route: '/shop', component: 'Shop', status: 'pending_ui_fix' },
  { label: 'Shopping Cart', originalFile: 'shopping-cart.html', route: '/cart', component: 'ShoppingCart', status: 'pending_ui_fix' },
  { label: 'Wishlist', originalFile: 'wishlist.html', route: '/wishlist', component: 'Wishlist', status: 'pending_ui_fix' }
];
